services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USE_LOCAL_DB=true
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - ./public/uploads:/app/public/uploads
    command: sh -c "pnpm db:generate && pnpm dev"
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  test:
    build: .
    environment:
      - NODE_ENV=test
      - USE_LOCAL_DB=true
      - PLAYWRIGHT_BASE_URL=http://app:3000
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - ./public/uploads:/app/public/uploads
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: ./scripts/test-docker.sh
    depends_on:
      app:
        condition: service_started
      postgres:
        condition: service_healthy
    profiles:
      - test

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wagashi_simulator
      - POSTGRES_USER=wagashi_user
      - POSTGRES_PASSWORD=wagashi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wagashi_user -d wagashi_simulator"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: