# This is a Docker Compose file for a production environment.
# It defines a single service named "app" that builds from the current directory.
# The service exposes port 3000, sets the environment variable NODE_ENV to production,
# mounts the current directory to /app in the container, and runs a command to build and start the application.
# docker compose -f compose.production.yml up
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./docker/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./docker/html:/usr/share/nginx/html
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:password@mysql:3306/wagashi_simulator
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./:/app
      - ./public/uploads:/app/public/uploads
    command: pnpm db:generate && pnpm start
    stdin_open: true
    tty: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wagashi_simulator
      - MYSQL_USER=wagashi_user
      - MYSQL_PASSWORD=wagashi_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password