# This is a Docker Compose file for a production environment.
# It defines a single service named "app" that builds from the current directory.
# The service exposes port 3000, sets the environment variable NODE_ENV to production,
# mounts the current directory to /app in the container, and runs a command to build and start the application.
# docker compose -f compose.production.yml up
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./docker/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./docker/html:/usr/share/nginx/html
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://wagashi_user:wagashi_password@postgres:5432/wagashi_simulator
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./public/uploads:/app/public/uploads
    command: pnpm start
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wagashi_simulator
      - POSTGRES_USER=wagashi_user
      - POSTGRES_PASSWORD=wagashi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: